#include <iostream>
#include <sstream>
#include <vector>
#include <limits>
#include <cmath>
using std::cout, std::cin, std::stringstream, std::vector;
typedef std::string string;

int main() {
    string chartString = R"(DC DC DC DC DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
CC DC DC DC DC DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
CC CC DC DC DC DC DC DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
CB CC DC DC DC DC DC DC DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
CB CC CC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF FF
CB CB CC CC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FF FF FF FF FF FF FF FF FF FF FF FF FF FF
BB CB CB CC CC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FF FF FF FF FF FF FF FF FF FF FF
BB BB CB CB CC CC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FF FF FF FF FF FF FF
BA BB BB CB CB CC CC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FF FF FF FF
BA BA BB CB CB CB CC CC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FF
AA BA BB BB CB CB CC CC CC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD
AA BA BA BB BB CB CB CC CC CC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD
AA AA BA BA BB BB CB CB CC CC CC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD
AA AA AA BA BA BB BB CB CB CC CC CC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD FD
AA AA AA BA BA BB BB BB CB CB CC CC CC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD FD FD
AA AA AA AA BA BA BB BB CB CB CB CC CC CC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD FD FD
AA AA AA AA AA BA BA BB BB CB CB CB CC CC CC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD FD FD FD
AA AA AA AA AA AA BA BA BB BB CB CB CB CC CC CC CC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD FD FD FD FD FD FD
AA AA AA AA AA AA BA BA BB BB BB CB CB CB CC CC CC CC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD FD FD FD
AA AA AA AA AA AA AA BA BA BB BB BB CB CB CB CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD FD
AA AA AA AA AA AA AA AA BA BA BB BB BB CB CB CB CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD
AA AA AA AA AA AA AA AA AA BA BA BB BB BB CB CB CB CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD
AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB CB CB CB CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD DD DD
AA AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB CB CB CB CB CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD DD DD
AA AA AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB CB CB CB CB CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD DD DD
AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB CB CB CB CB CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD DD DD
AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BB BB BB BB CB CB CB CB CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD DD DD
AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB BB CB CB CB CB CC CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DD DD DD DD DD
AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB BB CB CB CB CB CB CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DD DD DD
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB BB CB CB CB CB CB CC CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DD
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB BB CB CB CB CB CB CC CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB BB BB CB CB CB CB CB CC CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC DC DC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB BB BB CB CB CB CB CB CC CC CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC DC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BB BB BB BB BB CB CB CB CB CB CC CC CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC DC DC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BB BB BB BB CB CB CB CB CB CB CC CC CC CC CC CC CC DC DC DC DC DC DC DC DC DC DC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BB BB BB BB CB CB CB CB CB CB CC CC CC CC CC CC CC CC DC DC DC DC DC DC DC DC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BB BB BB BB BB CB CB CB CB CB CB CC CC CC CC CC CC CC CC DC DC DC DC DC DC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BB BB BB BB BB CB CB CB CB CB CB CC CC CC CC CC CC CC CC CC DC DC DC DC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BB BB BB BB BB CB CB CB CB CB CB CB CC CC CC CC CC CC CC CC DC DC DC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BB BB BB BB BB BB CB CB CB CB CB CB CB CC CC CC CC CC CC CC CC DC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BB BB BB BB BB BB CB CB CB CB CB CB CB CC CC CC CC CC CC CC CC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BB BB BB BB BB BB CB CB CB CB CB CB CB CC CC CC CC CC CC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BB BB BB BB BB BB CB CB CB CB CB CB CB CB CC CC CC CC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BB BB BB BB BB BB BB CB CB CB CB CB CB CB CB CC CC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BB BB BB BB BB BB CB CB CB CB CB CB CB CB CC
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BB BB BB BB BB BB BB CB CB CB CB CB CB CB
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BB BB BB BB BB BB BB CB CB CB CB CB CB
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BB BB BB BB BB BB BB CB CB CB CB
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BB BB BB BB BB BB BB BB CB CB
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BA BB BB BB BB BB BB BB CB
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BB BB BB BB BB BB BB
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BA BB BB BB BB BB
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BA BB BB BB BB
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BA BB BB
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BA BB
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA BA BA
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA BA
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA BA BA
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA BA
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA BA
AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA AA)";

    stringstream ss(chartString);
    string line;
    vector<std::vector<string>> chart;

    while (getline(ss, line)) {
        stringstream rowStream(line);
        vector<string> row;
        string value;

        while (rowStream >> value) {
            row.push_back(value);
        }

        chart.push_back(row);
    }

    int rows = chart.size();
    int columns = chart[0].size();

    double userInput;
    int score, average;
    cout << "Enter your score (30 to " << 30 + rows - 1 << "): ";
    while (!(cin >> userInput) || (userInput < 30) || (userInput > 90)) {
        cin.clear();
        
        cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
        
        cout << "Invalid input type or out of range! Enter a number in range: ";
    }

    score = std::round(userInput);
    //userInput = 45;

    cout << "Enter the average score (20 to " << 20 + columns - 1 << "): ";
    
    while (!(cin >> userInput) || (userInput < 20) || (userInput > 70)) {
        cin.clear();
        
        cin.ignore(std::numeric_limits<std::streamsize>::max(), '\n');
        
        cout << "Invalid input type or out of range! Enter a number in range: ";
    }
    average = std::round(userInput);

    int rowIndex = score - 30;
    int columnIndex = average - 20;

    cout << "The letter score of score " << score << " and average " << average << " is: " << chart[rowIndex][columnIndex] << std::endl;

    
    // if (score >= 30 && score < 30 + rows && average >= 20 && average < 20 + average) {
    //     
    //     int rowIndex = score - 30;
    //     int columnIndex = average - 20;

    //     cout << "The value at the intersection of row " << score
    //          << " and column " << average << " is: " << chart[rowIndex][columnIndex] << std::endl;
    // } else {
    //     cout << "Invalid score or average!" << std::endl;
    // }

    return 0;
}